# fly.toml app configuration file generated for backend-earnest-voice-5552 on 2026-05-14T00:44:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-earnest-voice-5552'
primary_region = 'lhr'

[build]
  [build.args]
    GO_VERSION = '1.26.0'

[env]
  DB_PATH = "/data/app.db"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [[http_service.checks]]
    interval = "60s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[mounts]
  source = "ashbythorpe_data"
  destination = "/data"
