name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: opc
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd ~/ashbythorpe.com

            git pull origin main

            cd backend

            mkdir -p ~/.config/containers/systemd/

            cp ./containers/*.container ~/.config/containers/systemd/

            podman build -t localhost/ashbythorpe-backend:latest .

            systemctl --user daemon-reload

            systemctl --user restart web tunnel
